version: '3.7'

services:
  database:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - node-crud-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodecrud
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  app:
    build: .
    command: 'npm run dev'
    container_name: node-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  node-crud-data:
    name: nodecrud_mysql_data
    driver: local
